{
  try {
    r.run();
    Assert.fail("Expected exception type " + expectedExceptionType.getName() + " was not thrown (message="+ message+ ")");
  }
 catch (  Throwable e) {
    Assert.assertTrue("Expected exception type was " + expectedExceptionType.getName() + " but caught "+ e+ " (message="+ message+ ")",expectedExceptionType.isAssignableFrom(e.getClass()));
    if (expectedExceptionMessageRegex != null) {
      MoreAsserts.assertContainsRegex(expectedExceptionMessageRegex,e.getMessage());
    }
  }
}
