{
  fail("method in ProtectedConstructorTest run unexpectedly");
}
