{
  try {
    r.run();
    Assert.fail("Expected exception type " + expectedExceptionType.getClass().getName() + " was not thrown");
  }
 catch (  Throwable e) {
    Assert.assertTrue("Expected exception type was " + expectedExceptionType.getClass().getName() + " but caught "+ e.getClass().getName(),expectedExceptionType.isAssignableFrom(e.getClass()));
    if (expectedExceptionMessageRegex != null) {
      MoreAsserts.assertContainsRegex(expectedExceptionMessageRegex,e.getMessage());
    }
  }
}
